### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by niconoe** [AtlasOfLivingAustralia/ala-install#72] opened 2015-08-19 09:09 UTC
Hi guys,

Those days, I'm getting a 404 error when running the script:

TASK: [biocache-service | download from maven repo] ***************************
failed: [vagrant1] => {"dest": "/var/lib/tomcat7/webapps/biocache-service.war", "failed": true, "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://repository.gbif.org/service/local/artifact/maven/redirect?r=ala-release&g=au.org.ala&a=biocache-service&v=LATEST&e=war&c="}
msg: Request failed

FATAL: all hosts have already failed -- aborting

Indeed, manually connection to this URL also gives a 404 error. What can I do?

Thanks,

Nicolas

**Comment by djtfmartin** [comment] 2015-08-19 09:43
Thanks Nicolas.

I had this last week and havent resolved it yet.

One potential "workaround" is to use the ALA repo instead. This can be done with a change in the inventory.

```
use_gbif_nexus=false
```

I say "workaround" as this might lead to some timeout errors (which is why we are using the GBIF repo in the first place).

**Comment by djtfmartin** [comment] 2016-04-05 07:50
Closing. Created #101 as the issue is still there.

**Closed by djtfmartin** 2016-04-05 07:50 UTC
